[package]
name = "e-voting"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clearscreen = "3.0.0"
#clearscreen = "2.0.1"
bcrypt = "0.15.1"
#bcrypt = "0.10.0"
sha2 = "0.10.0"
hex = "0.4.3"
